# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TypeScript

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.x
      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build:gql
        env:
          SHOPIFY_ADMIN_API_GRAPHQL_SCHEMA_SECRET: ${{ secrets.SHOPIFY_ADMIN_API_GRAPHQL_SCHEMA_SECRET }}
      - run: npm run type-check
      - run: npm run lint
      - run: npm test
